[project]
name = "faer-nivi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai[google-genai,tools]>=1.9.3",
    "litellm>=1.75.3",
    "pymongo>=4.16.0",
]
